@echo off
ECHO rewriting scene files

ren scn_town_1_alley.sco scn_town_67_alley.sco
ren scn_town_2_alley.sco scn_town_68_alley.sco
ren scn_town_3_alley.sco scn_town_69_alley.sco
ren scn_town_4_alley.sco scn_town_70_alley.sco
ren scn_town_5_alley.sco scn_town_71_alley.sco
ren scn_town_6_alley.sco scn_town_72_alley.sco
ren scn_town_7_alley.sco scn_town_73_alley.sco
ren scn_town_8_alley.sco scn_town_52_alley.sco
ren scn_town_9_alley.sco scn_town_53_alley.sco
ren scn_town_10_alley.sco scn_town_54_alley.sco
ren scn_town_11_alley.sco scn_town_55_alley.sco
ren scn_town_12_alley.sco scn_town_56_alley.sco
ren scn_town_13_alley.sco scn_town_57_alley.sco
ren scn_town_14_alley.sco scn_town_58_alley.sco
ren scn_town_15_alley.sco scn_town_59_alley.sco
ren scn_town_16_alley.sco scn_town_60_alley.sco
ren scn_town_17_alley.sco scn_town_61_alley.sco
ren scn_town_18_alley.sco scn_town_62_alley.sco
ren scn_town_19_alley.sco scn_town_63_alley.sco
ren scn_town_20_alley.sco scn_town_64_alley.sco
ren scn_town_21_alley.sco scn_town_65_alley.sco
ren scn_town_22_alley.sco scn_town_66_alley.sco
ren scn_town_1_arena.sco scn_town_67_arena.sco
ren scn_town_2_arena.sco scn_town_68_arena.sco
ren scn_town_3_arena.sco scn_town_69_arena.sco
ren scn_town_4_arena.sco scn_town_70_arena.sco
ren scn_town_5_arena.sco scn_town_71_arena.sco
ren scn_town_6_arena.sco scn_town_72_arena.sco
ren scn_town_7_arena.sco scn_town_73_arena.sco
ren scn_town_8_arena.sco scn_town_52_arena.sco
ren scn_town_9_arena.sco scn_town_53_arena.sco
ren scn_town_10_arena.sco scn_town_54_arena.sco
ren scn_town_11_arena.sco scn_town_55_arena.sco
ren scn_town_12_arena.sco scn_town_56_arena.sco
ren scn_town_13_arena.sco scn_town_57_arena.sco
ren scn_town_14_arena.sco scn_town_58_arena.sco
ren scn_town_15_arena.sco scn_town_59_arena.sco
ren scn_town_16_arena.sco scn_town_60_arena.sco
ren scn_town_17_arena.sco scn_town_61_arena.sco
ren scn_town_18_arena.sco scn_town_62_arena.sco
ren scn_town_19_arena.sco scn_town_63_arena.sco
ren scn_town_20_arena.sco scn_town_64_arena.sco
ren scn_town_21_arena.sco scn_town_65_arena.sco
ren scn_town_22_arena.sco scn_town_66_arena.sco
ren scn_town_1_castle.sco scn_town_67_castle.sco
ren scn_town_2_castle.sco scn_town_68_castle.sco
ren scn_town_3_castle.sco scn_town_69_castle.sco
ren scn_town_4_castle.sco scn_town_70_castle.sco
ren scn_town_5_castle.sco scn_town_71_castle.sco
ren scn_town_6_castle.sco scn_town_72_castle.sco
ren scn_town_7_castle.sco scn_town_73_castle.sco
ren scn_town_8_castle.sco scn_town_52_castle.sco
ren scn_town_9_castle.sco scn_town_53_castle.sco
ren scn_town_10_castle.sco scn_town_54_castle.sco
ren scn_town_11_castle.sco scn_town_55_castle.sco
ren scn_town_12_castle.sco scn_town_56_castle.sco
ren scn_town_13_castle.sco scn_town_57_castle.sco
ren scn_town_14_castle.sco scn_town_58_castle.sco
ren scn_town_15_castle.sco scn_town_59_castle.sco
ren scn_town_16_castle.sco scn_town_60_castle.sco
ren scn_town_17_castle.sco scn_town_61_castle.sco
ren scn_town_18_castle.sco scn_town_62_castle.sco
ren scn_town_19_castle.sco scn_town_63_castle.sco
ren scn_town_20_castle.sco scn_town_64_castle.sco
ren scn_town_21_castle.sco scn_town_65_castle.sco
ren scn_town_22_castle.sco scn_town_66_castle.sco
ren scn_town_1_center.sco scn_town_67_center.sco
ren scn_town_2_center.sco scn_town_68_center.sco
ren scn_town_3_center.sco scn_town_69_center.sco
ren scn_town_4_center.sco scn_town_70_center.sco
ren scn_town_5_center.sco scn_town_71_center.sco
ren scn_town_6_center.sco scn_town_72_center.sco
ren scn_town_7_center.sco scn_town_73_center.sco
ren scn_town_8_center.sco scn_town_52_center.sco
ren scn_town_9_center.sco scn_town_53_center.sco
ren scn_town_10_center.sco scn_town_54_center.sco
ren scn_town_11_center.sco scn_town_55_center.sco
ren scn_town_12_center.sco scn_town_56_center.sco
ren scn_town_13_center.sco scn_town_57_center.sco
ren scn_town_14_center.sco scn_town_58_center.sco
ren scn_town_15_center.sco scn_town_59_center.sco
ren scn_town_16_center.sco scn_town_60_center.sco
ren scn_town_17_center.sco scn_town_61_center.sco
ren scn_town_18_center.sco scn_town_62_center.sco
ren scn_town_19_center.sco scn_town_63_center.sco
ren scn_town_20_center.sco scn_town_64_center.sco
ren scn_town_21_center.sco scn_town_65_center.sco
ren scn_town_22_center.sco scn_town_66_center.sco
ren scn_town_1_prison.sco scn_town_67_prison.sco
ren scn_town_2_prison.sco scn_town_68_prison.sco
ren scn_town_3_prison.sco scn_town_69_prison.sco
ren scn_town_4_prison.sco scn_town_70_prison.sco
ren scn_town_5_prison.sco scn_town_71_prison.sco
ren scn_town_6_prison.sco scn_town_72_prison.sco
ren scn_town_7_prison.sco scn_town_73_prison.sco
ren scn_town_8_prison.sco scn_town_52_prison.sco
ren scn_town_9_prison.sco scn_town_53_prison.sco
ren scn_town_10_prison.sco scn_town_54_prison.sco
ren scn_town_11_prison.sco scn_town_55_prison.sco
ren scn_town_12_prison.sco scn_town_56_prison.sco
ren scn_town_13_prison.sco scn_town_57_prison.sco
ren scn_town_14_prison.sco scn_town_58_prison.sco
ren scn_town_15_prison.sco scn_town_59_prison.sco
ren scn_town_16_prison.sco scn_town_60_prison.sco
ren scn_town_17_prison.sco scn_town_61_prison.sco
ren scn_town_18_prison.sco scn_town_62_prison.sco
ren scn_town_19_prison.sco scn_town_63_prison.sco
ren scn_town_20_prison.sco scn_town_64_prison.sco
ren scn_town_21_prison.sco scn_town_65_prison.sco
ren scn_town_22_prison.sco scn_town_66_prison.sco
ren scn_town_1_store.sco scn_town_67_store.sco
ren scn_town_2_store.sco scn_town_68_store.sco
ren scn_town_3_store.sco scn_town_69_store.sco
ren scn_town_4_store.sco scn_town_70_store.sco
ren scn_town_5_store.sco scn_town_71_store.sco
ren scn_town_6_store.sco scn_town_72_store.sco
ren scn_town_7_store.sco scn_town_73_store.sco
ren scn_town_8_store.sco scn_town_52_store.sco
ren scn_town_9_store.sco scn_town_53_store.sco
ren scn_town_10_store.sco scn_town_54_store.sco
ren scn_town_11_store.sco scn_town_55_store.sco
ren scn_town_12_store.sco scn_town_56_store.sco
ren scn_town_13_store.sco scn_town_57_store.sco
ren scn_town_14_store.sco scn_town_58_store.sco
ren scn_town_15_store.sco scn_town_59_store.sco
ren scn_town_16_store.sco scn_town_60_store.sco
ren scn_town_17_store.sco scn_town_61_store.sco
ren scn_town_18_store.sco scn_town_62_store.sco
ren scn_town_19_store.sco scn_town_63_store.sco
ren scn_town_20_store.sco scn_town_64_store.sco
ren scn_town_21_store.sco scn_town_65_store.sco
ren scn_town_22_store.sco scn_town_66_store.sco
ren scn_town_1_tavern.sco scn_town_67_tavern.sco
ren scn_town_2_tavern.sco scn_town_68_tavern.sco
ren scn_town_3_tavern.sco scn_town_69_tavern.sco
ren scn_town_4_tavern.sco scn_town_70_tavern.sco
ren scn_town_5_tavern.sco scn_town_71_tavern.sco
ren scn_town_6_tavern.sco scn_town_72_tavern.sco
ren scn_town_7_tavern.sco scn_town_73_tavern.sco
ren scn_town_8_tavern.sco scn_town_52_tavern.sco
ren scn_town_9_tavern.sco scn_town_53_tavern.sco
ren scn_town_10_tavern.sco scn_town_54_tavern.sco
ren scn_town_11_tavern.sco scn_town_55_tavern.sco
ren scn_town_12_tavern.sco scn_town_56_tavern.sco
ren scn_town_13_tavern.sco scn_town_57_tavern.sco
ren scn_town_14_tavern.sco scn_town_58_tavern.sco
ren scn_town_15_tavern.sco scn_town_59_tavern.sco
ren scn_town_16_tavern.sco scn_town_60_tavern.sco
ren scn_town_17_tavern.sco scn_town_61_tavern.sco
ren scn_town_18_tavern.sco scn_town_62_tavern.sco
ren scn_town_19_tavern.sco scn_town_63_tavern.sco
ren scn_town_20_tavern.sco scn_town_64_tavern.sco
ren scn_town_21_tavern.sco scn_town_65_tavern.sco
ren scn_town_22_tavern.sco scn_town_66_tavern.sco
ren scn_town_1_walls.sco scn_town_67_walls.sco
ren scn_town_2_walls.sco scn_town_68_walls.sco
ren scn_town_3_walls.sco scn_town_69_walls.sco
ren scn_town_4_walls.sco scn_town_70_walls.sco
ren scn_town_5_walls.sco scn_town_71_walls.sco
ren scn_town_6_walls.sco scn_town_72_walls.sco
ren scn_town_7_walls.sco scn_town_73_walls.sco
ren scn_town_8_walls.sco scn_town_52_walls.sco
ren scn_town_9_walls.sco scn_town_53_walls.sco
ren scn_town_10_walls.sco scn_town_54_walls.sco
ren scn_town_11_walls.sco scn_town_55_walls.sco
ren scn_town_12_walls.sco scn_town_56_walls.sco
ren scn_town_13_walls.sco scn_town_57_walls.sco
ren scn_town_14_walls.sco scn_town_58_walls.sco
ren scn_town_15_walls.sco scn_town_59_walls.sco
ren scn_town_16_walls.sco scn_town_60_walls.sco
ren scn_town_17_walls.sco scn_town_61_walls.sco
ren scn_town_18_walls.sco scn_town_62_walls.sco
ren scn_town_19_walls.sco scn_town_63_walls.sco
ren scn_town_20_walls.sco scn_town_64_walls.sco
ren scn_town_21_walls.sco scn_town_65_walls.sco
ren scn_town_22_walls.sco scn_town_66_walls.sco



ECHO Renaming Complete

pause